### ISSUE TITLE
Add a method to profile a series of hyperparameter runs

### ISSUE THREAD

**Issue by AOS55** [AOS55/Fixedwing-Airsim#17]
Documented quite well in [TensorFlow's tensorboard docs](https://www.tensorflow.org/tensorboard/hyperparameter_tuning_with_hparams). The idea is we can set a series of tensorboard parameters and then use these to experiment with the effect of changing a variety of parameters. There is also [pytorch documentation for this](https://pytorch.org/docs/stable/tensorboard.html) using: `add_hparams(hparam_dict, metric_dict, hparam_domain_discrete=None, run_name=None)` contained as a method in `torch.utils.tensorboard`.

**Comment by zclyaya** [comment]
hello，I meet this problem, but i do not konw how to solve it, can you help me? I do not konw the reason and where is wrong,  I am looking forword to you reply. 
D:\Anaconda3\envs\Airsim\python.exe E:\computer\GitHub\Fixedwing-Airsim-master\src\main.py

In file D:/Anaconda3/envs/Airsim/Lib/site-packages/jsbsim/aircraft/x8/x8.xml: line 80
Engine location ignored, only thruster location is used.

In file D:/Anaconda3/envs/Airsim/Lib/site-packages/jsbsim/aircraft/x8/x8.xml: line 85
Engine orientation ignored, only thruster orientation is used.
Traceback (most recent call last):
File "E:\computer\GitHub\Fixedwing-Airsim-master\src\main.py", line 218, in
run_simulator()
File "E:\computer\GitHub\Fixedwing-Airsim-master\src\main.py", line 196, in run_simulator
env.simulation_loop(rectangle)
File "E:\computer\GitHub\Fixedwing-Airsim-master\src\main.py", line 93, in simulation_loop
image.get_np_image(image_type=airsim.ImageType.Scene)
File "E:\computer\GitHub\Fixedwing-Airsim-master\src\image_processing.py", line 44, in get_np_image
False)])
File "D:\Anaconda3\envs\Airsim\lib\site-packages\airsim\client.py", line 295, in simGetImages
responses_raw = self.client.call("simGetImages", requests, vehicle_name)
File "D:\Anaconda3\envs\Airsim\lib\site-packages\msgpackrpc\session.py", line 41, in call
return self.send_request(method, args).get()
File "D:\Anaconda3\envs\Airsim\lib\site-packages\msgpackrpc\future.py", line 45, in get
raise error.RPCError(self._error)
msgpackrpc.error.RPCError: rpclib: client error C0002: Function 'simGetImages' was called with an invalid number of arguments. Expected: 2, got: 3

 JSBSim Flight Dynamics Model v1.1.13 [GitHub build 986/commit a09715f01b9e568ce75ca2635ba0a78ce57f7cdd] Dec  3 2022 12:36:17
        [JSBSim-ML v2.0]
JSBSim startup beginning ...

Connected!
Client Ver:1 (Min Req: 1), Server Ver:1 (Min Req: 1)

Process finished with exit code
