### ISSUE TITLE
The JSBSim path problem

### ISSUE THREAD

**Issue by saj237** [AOS55/Fixedwing-Airsim#36]
![image](https://user-images.githubusercontent.com/112924324/195802677-8bf96c2a-1d1b-4803-90fb-7a55163998e6.png)
How to modify the jsbsim path of this  jsbsim_simulator.py?
I moved the model file to the corresponding location according to the operation, but since the path of jsbsim is different from yours, run main.py reported the following error:
RuntimeError: JSBSim could not find specified model name: x8

**Comment by AOS55** [comment]
I need to go in and refactor this when I get the time. 
- For now the [x8 path is in the JSBSim ID key](https://github.com/AOS55/Fixedwing-Airsim/blob/bda514232ee3a68e350c3c2023522343a4b71579/src/jsbsim_aircraft.py#L25)
- This is loaded in with [fdm.load_model](https://github.com/AOS55/Fixedwing-Airsim/blob/bda514232ee3a68e350c3c2023522343a4b71579/src/jsbsim_aircraft.py#L25)
- Perhaps look at where the aircraft folder is in your JSBSim path, also I'm not sure if the double JSBSim path `\JSBSim\JSBSim` has an impact. 
- You could also see where the location of the JSBSim package loaded is by running:
`print(os.path.dirname(jsbsim.__file__))` as I think it is looking for the aircraft file one level up.

**Comment by saj237** [comment]
Thank you! I will try.

**Comment by saj237** [comment]
![image](https://user-images.githubusercontent.com/112924324/195851822-f1d6c2aa-8b26-48d8-a1b0-fe0a9854836b.png)
Sorry, I can't find the electric800w.xml file in your Fixedwing-Airsim-master file. Did I miss something? I can only find the electric800.xml file in the x8 folder.

**Comment by AOS55** [comment]
Hey yep file had wrong name it should be electric800W.xml you [can see it in the x8.xml](https://github.com/AOS55/Fixedwing-Airsim/blob/c5054486fb05dc67668b123c7789e399c8d4ce02/x8/x8.xml#L79) file for JSBSim

**Comment by AOS55** [comment]
I have now changed the name

**Comment by zclyaya** [comment]
Traceback (most recent call last):
  File "D:\Fixedwing-Airsim-master\src\main.py", line 3, in <module>
    import airsim

hi ,how to solve this problem?

**Comment by zclyaya** [comment]
> Thank you! I will try. hi,I meet same problem, can you help me ? I modify the jsbsim path to "d:\JSBSim",  run main.py  in pycharm reported the following error:

C:\Users\zcl\.conda\envs\zclpytorch\python.exe D:\Fixedwing-Airsim-master\src\main.py 

In file d:/JSBSim/aircraft/x8/x8.xml: line 80
Engine location ignored, only thruster location is used.

In file d:/JSBSim/aircraft/x8/x8.xml: line 85
Engine orientation ignored, only thruster orientation is used.
Traceback (most recent call last):
  File "D:\Fixedwing-Airsim-master\src\main.py", line 217, in <module>
    run_simulator()
  File "D:\Fixedwing-Airsim-master\src\main.py", line 195, in run_simulator
    env.simulation_loop(rectangle)
  File "D:\Fixedwing-Airsim-master\src\main.py", line 92, in simulation_loop
    image.get_np_image(image_type=airsim.ImageType.Scene)
  File "D:\Fixedwing-Airsim-master\src\image_processing.py", line 44, in get_np_image
    False)])
  File "C:\Users\zcl\.conda\envs\zclpytorch\lib\site-packages\airsim\client.py", line 295, in simGetImages
    responses_raw = self.client.call("simGetImages", requests, vehicle_name)
  File "C:\Users\zcl\.conda\envs\zclpytorch\lib\site-packages\msgpackrpc\session.py", line 41, in call
    return self.send_request(method, args).get()
  File "C:\Users\zcl\.conda\envs\zclpytorch\lib\site-packages\msgpackrpc\future.py", line 45, in get
    raise error.RPCError(self._error)
msgpackrpc.error.RPCError: rpclib: client error C0002: Function 'simGetImages' was called with an invalid number of arguments. Expected: 2, got: 3


     JSBSim Flight Dynamics Model v1.1.11 [GitHub build 741/commit 10e077b486c42d38e76d1dd7f0aeb744f92d96a0] Feb 13 2022 12:30:25
            [JSBSim-ML v2.0]

JSBSim startup beginning ...

Connected!
Client Ver:1 (Min Req: 1), Server Ver:1 (Min Req: 1)


Process finished with exit code 1

**Comment by nechtobolshee** [comment]
> > Thank you! I will try. hi,I meet same problem, can you help me ? I modify the jsbsim path to "d:\JSBSim",  run main.py  in pycharm reported the following error:
> 
> C:\Users\zcl.conda\envs\zclpytorch\python.exe D:\Fixedwing-Airsim-master\src\main.py
> 
> In file d:/JSBSim/aircraft/x8/x8.xml: line 80 Engine location ignored, only thruster location is used.
> 
> In file d:/JSBSim/aircraft/x8/x8.xml: line 85 Engine orientation ignored, only thruster orientation is used. Traceback (most recent call last): File "D:\Fixedwing-Airsim-master\src\main.py", line 217, in run_simulator() File "D:\Fixedwing-Airsim-master\src\main.py", line 195, in run_simulator env.simulation_loop(rectangle) File "D:\Fixedwing-Airsim-master\src\main.py", line 92, in simulation_loop image.get_np_image(image_type=airsim.ImageType.Scene) File "D:\Fixedwing-Airsim-master\src\image_processing.py", line 44, in get_np_image False)]) File "C:\Users\zcl.conda\envs\zclpytorch\lib\site-packages\airsim\client.py", line 295, in simGetImages responses_raw = self.client.call("simGetImages", requests, vehicle_name) File "C:\Users\zcl.conda\envs\zclpytorch\lib\site-packages\msgpackrpc\session.py", line 41, in call return self.send_request(method, args).get() File "C:\Users\zcl.conda\envs\zclpytorch\lib\site-packages\msgpackrpc\future.py", line 45, in get raise error.RPCError(self._error) msgpackrpc.error.RPCError: rpclib: client error C0002: Function 'simGetImages' was called with an invalid number of arguments. Expected: 2, got: 3
> 
> ```
>  JSBSim Flight Dynamics Model v1.1.11 [GitHub build 741/commit 10e077b486c42d38e76d1dd7f0aeb744f92d96a0] Feb 13 2022 12:30:25
>         [JSBSim-ML v2.0]
> ```
> 
> JSBSim startup beginning ...
> 
> Connected! Client Ver:1 (Min Req: 1), Server Ver:1 (Min Req: 1)
> 
> Process finished with exit code 1

The same problem. Have u fixed it? 
@AOS55
